// Requirement: Paired theme combos for simplified DaisyUI theme selection.
// Approach: Two curated combos (Mono + Luxe), each pairing a light and dark theme.
//   User picks a combo; dark/light toggle switches between the combo's themes.
// Alternatives:
//   - Independent per-mode selection (16 themes): Rejected — too many choices, simplified to combos.
//   - Single theme with no combo: Rejected — user wants at least two visual options.

// Meta theme-color for PWA status bar — matches each theme's primary or base color.
// AUTO-GENERATED by scripts/generate-theme-meta.mjs from DaisyUI oklch values.
// Do not edit metaColor values manually — run the script after DaisyUI updates.

export const themeCombos = [
  {
    id: 'mono',
    name: 'Mono',
    description: 'Clean & minimal',
    light: { id: 'lofi', metaColor: '#ebebeb' },
    dark: { id: 'black', metaColor: '#000000' },
  },
  {
    id: 'luxe',
    name: 'Luxe',
    description: 'Rich & elegant',
    light: { id: 'fantasy', metaColor: '#6d0076' },
    dark: { id: 'luxury', metaColor: '#09090b' },
  },
]

export const DEFAULT_COMBO = 'luxe'

// Look up meta theme-color for a given theme ID.
// Falls back to neutral values if theme not found.
export function getMetaColor(themeId) {
  for (const combo of themeCombos) {
    if (combo.light.id === themeId) return combo.light.metaColor
    if (combo.dark.id === themeId) return combo.dark.metaColor
  }
  return '#808080'
}

// Look up combo by ID — returns combo object or default combo.
export function getCombo(comboId) {
  return themeCombos.find(c => c.id === comboId) || themeCombos[0]
}
