// Requirement: Independent per-mode DaisyUI theme selection.
// Approach: Curated lists of light and dark themes with metadata for UI and PWA theming.
//   Each mode remembers its own theme choice via localStorage.
// Alternatives:
//   - Paired combos (glow-props pattern): Rejected — user wants independent selection.
//   - All 30+ DaisyUI themes: Rejected — too many, some are novelty. Curated for quality.

// Meta theme-color for PWA status bar — matches each theme's primary or base color.
// AUTO-GENERATED by scripts/generate-theme-meta.mjs from DaisyUI oklch values.
// Do not edit metaColor values manually — run the script after DaisyUI updates.

export const lightThemes = [
  { id: 'nord', name: 'Nord', description: 'Cool blue-gray', metaColor: '#5e81ac' },
  { id: 'lofi', name: 'Lo-Fi', description: 'Minimal mono', metaColor: '#ebebeb' },
  { id: 'emerald', name: 'Emerald', description: 'Fresh green', metaColor: '#66cc8a' },
  { id: 'cupcake', name: 'Cupcake', description: 'Soft pastels', metaColor: '#44ebd3' },
  { id: 'garden', name: 'Garden', description: 'Warm green', metaColor: '#bebdbd' },
  { id: 'autumn', name: 'Autumn', description: 'Earthy warm', metaColor: '#8c0327' },
  { id: 'pastel', name: 'Pastel', description: 'Soft muted', metaColor: '#e9d4ff' },
  { id: 'caramellatte', name: 'Caramel', description: 'Warm brown', metaColor: '#ffd6a7' },
]

export const darkThemes = [
  { id: 'night', name: 'Night', description: 'Deep blue', metaColor: '#0f172a' },
  { id: 'black', name: 'Black', description: 'True OLED', metaColor: '#000000' },
  { id: 'forest', name: 'Forest', description: 'Deep green', metaColor: '#1b1717' },
  { id: 'dracula', name: 'Dracula', description: 'Bold purple', metaColor: '#282a36' },
  { id: 'dim', name: 'Dim', description: 'Muted warm', metaColor: '#2a303c' },
  { id: 'synthwave', name: 'Synthwave', description: 'Neon retro', metaColor: '#09002f' },
  { id: 'luxury', name: 'Luxury', description: 'Dark gold', metaColor: '#09090b' },
  { id: 'coffee', name: 'Coffee', description: 'Dark roast', metaColor: '#261b25' },
]

export const DEFAULT_LIGHT_THEME = 'lofi'
export const DEFAULT_DARK_THEME = 'black'

// Look up meta theme-color for a given theme ID.
// Falls back to neutral values if theme not found.
export function getMetaColor(themeId) {
  const all = [...lightThemes, ...darkThemes]
  const found = all.find(t => t.id === themeId)
  return found?.metaColor ?? '#808080'
}
